---
    
- name: set openvpn service name
  set_fact:
    service_name: "openvpn@server"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7'


- name: set openvpn service name
  set_fact:
    service_name: "openvpn@server"
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution_major_version == '16'


- name: set openvpn service name
  set_fact:
    service_name: "openvpn"
  when: service_name is not defined


- name: create group for open vpn
  group: 
    name: "{{openvpn_group}}"
    system: yes
    state: present


- name: create user for open vpn
  user: 
    name: "{{openvpn_user}}" 
    comment: "Open VPN"
    group: "{{openvpn_group}}"
    system: yes
    state: present
    createhome: no


- name: installing packages
  include: install_packages.yml


- name: create openvpn directories
  file: 
    path: "{{item}}" 
    state: directory 
    mode: 0750
    owner: root
    group: "{{openvpn_group}}"
  with_items:
    - "{{ openvpn_keydir }}"
    - "{{ openvpn_configdir }}"
    - "{{ openvpn_clientconfig_dir }}"
    - "{{ openvpn_client_certificates_dir }}"


- include: server_certs_gen.yml


- name: create openvpn server config
  template:
    dest: "{{openvpn_configdir}}/server.conf"
    src: server.conf.j2
  notify: 
  - openvpn restart


- name: Ensure OpenVPN is started
  service: 
    name: "{{ service_name }}"
    state: started 
    enabled: yes


- include: client_configs.yml
